# Generated by Django 5.2 on 2025-12-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_invitation'),
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameModel(
            old_name='Membership',
            new_name='OrganizationUser',
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[],
            options={
                'verbose_name': 'Deprecated membership',
                'verbose_name_plural': 'Deprecated memberships',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.organizationuser',),
        ),
    ]

