# Generated by Django 5.2 on 2025-12-06 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_membership_to_organization_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
